// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsn2tC0UirEnjPLSgVYvLNTGY1Z9GQoi0',
    appId: '1:657034913156:web:6cf3497ff0d637328769d1',
    messagingSenderId: '657034913156',
    projectId: 'pharma-apps',
    authDomain: 'pharma-apps.firebaseapp.com',
    storageBucket: 'pharma-apps.firebasestorage.app',
    measurementId: 'G-VTR79DH4ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZuHBzN1X9kfQNSCXkWb70FbGXDT8e7V8',
    appId: '1:657034913156:android:45f24f62150c3de98769d1',
    messagingSenderId: '657034913156',
    projectId: 'pharma-apps',
    storageBucket: 'pharma-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJZQwnYz080hy58WeJILCjWyqquXAVAjg',
    appId: '1:657034913156:ios:4ad4c768fb9a33b68769d1',
    messagingSenderId: '657034913156',
    projectId: 'pharma-apps',
    storageBucket: 'pharma-apps.firebasestorage.app',
    iosClientId: '657034913156-h1u3m5iaov409aqr8a6ci5uoehh0tom0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacyDesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJZQwnYz080hy58WeJILCjWyqquXAVAjg',
    appId: '1:657034913156:ios:4ad4c768fb9a33b68769d1',
    messagingSenderId: '657034913156',
    projectId: 'pharma-apps',
    storageBucket: 'pharma-apps.firebasestorage.app',
    iosClientId: '657034913156-h1u3m5iaov409aqr8a6ci5uoehh0tom0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacyDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsn2tC0UirEnjPLSgVYvLNTGY1Z9GQoi0',
    appId: '1:657034913156:web:24178356ae49aea18769d1',
    messagingSenderId: '657034913156',
    projectId: 'pharma-apps',
    authDomain: 'pharma-apps.firebaseapp.com',
    storageBucket: 'pharma-apps.firebasestorage.app',
    measurementId: 'G-EVHZHKL6Y4',
  );

}