// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbRJpPIXvI11zYIF8_kg_po4XokPAX61U',
    appId: '1:809487153088:web:5de4770b3fab8be4bffa25',
    messagingSenderId: '809487153088',
    projectId: 'pharmafind-fd452',
    authDomain: 'pharmafind-fd452.firebaseapp.com',
    storageBucket: 'pharmafind-fd452.firebasestorage.app',
    measurementId: 'G-76Z70T8WGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgB3yaONGBon6k07AVpkYPv_cB0TTWYvA',
    appId: '1:809487153088:android:271dc705bb3f6bfdbffa25',
    messagingSenderId: '809487153088',
    projectId: 'pharmafind-fd452',
    storageBucket: 'pharmafind-fd452.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj6mj7RPCf2Hy6rcEgZgwV3nRQ2WzcCLI',
    appId: '1:809487153088:ios:c3452dcf286325f8bffa25',
    messagingSenderId: '809487153088',
    projectId: 'pharmafind-fd452',
    storageBucket: 'pharmafind-fd452.firebasestorage.app',
    androidClientId: '809487153088-aod847c8p38p76b93v8pgkg03estjits.apps.googleusercontent.com',
    iosClientId: '809487153088-r09dvieq7ocdh7ghtlmm7tons881876j.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacyDesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj6mj7RPCf2Hy6rcEgZgwV3nRQ2WzcCLI',
    appId: '1:809487153088:ios:c3452dcf286325f8bffa25',
    messagingSenderId: '809487153088',
    projectId: 'pharmafind-fd452',
    storageBucket: 'pharmafind-fd452.firebasestorage.app',
    androidClientId: '809487153088-aod847c8p38p76b93v8pgkg03estjits.apps.googleusercontent.com',
    iosClientId: '809487153088-r09dvieq7ocdh7ghtlmm7tons881876j.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacyDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbRJpPIXvI11zYIF8_kg_po4XokPAX61U',
    appId: '1:809487153088:web:7c3d599ce9b00a58bffa25',
    messagingSenderId: '809487153088',
    projectId: 'pharmafind-fd452',
    authDomain: 'pharmafind-fd452.firebaseapp.com',
    storageBucket: 'pharmafind-fd452.firebasestorage.app',
    measurementId: 'G-29W9Q9C8EJ',
  );

}